FROM alpine:3.20
RUN apk add --no-cache wireguard-tools iproute2 curl bash jq iputils iptables ip6tables
COPY entrypoint-client.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
